metadata:
  name: build-execution-environment
  # you can add additional metadata here
  instructional: true
spec:
  displayName: Building an automation execution environment
  durationMinutes: 10
  # Optional type section, will display as a tile on the card
  type:
    text: Automation Content
    # 'blue' | 'cyan' | 'green' | 'orange' | 'purple' | 'red' | 'grey'
    color: grey
  # - The icon defined as a base64 value. Example flow:
  # 1. Find an .svg you want to use, like from here: https://www.patternfly.org/v4/guidelines/icons/#all-icons
  # 2. Upload the file here and encode it (output format - plain text): https://base64.guru/converter/encode/image
  # 3. compose - `icon: data:image/svg+xml;base64,<base64 string from step 2>`
  # - If empty string (icon: ''), will use a default rocket icon
  # - If set to null (icon: ~) will not show an icon
  icon: data:image/svg+xml;base64,PCEtLSBHZW5lcmF0ZWQgYnkgSWNvTW9vbi5pbyAtLT4KPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjUxMiIgaGVpZ2h0PSI1MTIiIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj4KPHRpdGxlPjwvdGl0bGU+CjxnIGlkPSJpY29tb29uLWlnbm9yZSI+CjwvZz4KPHBhdGggZD0iTTQ0OCA2NHY0MTZoLTMzNmMtMjYuNTEzIDAtNDgtMjEuNDktNDgtNDhzMjEuNDg3LTQ4IDQ4LTQ4aDMwNHYtMzg0aC0zMjBjLTM1LjE5OSAwLTY0IDI4LjgtNjQgNjR2Mzg0YzAgMzUuMiAyOC44MDEgNjQgNjQgNjRoMzg0di00NDhoLTMyeiI+PC9wYXRoPgo8cGF0aCBkPSJNMTEyLjAyOCA0MTZ2MGMtMC4wMDkgMC4wMDEtMC4wMTkgMC0wLjAyOCAwLTguODM2IDAtMTYgNy4xNjMtMTYgMTZzNy4xNjQgMTYgMTYgMTZjMC4wMDkgMCAwLjAxOS0wLjAwMSAwLjAyOC0wLjAwMXYwLjAwMWgzMDMuOTQ1di0zMmgtMzAzLjk0NXoiPjwvcGF0aD4KPC9zdmc+Cg==
  
  description: |-
    Build, view, and sync an environment.

    Persona: Platform administrator, Automation developer
  introduction: |-
   All automation in Red Hat Ansible Automation Platform runs on container images called automation execution environments. 
   Automation execution environments create a common language for communicating automation dependencies, and offer a standard way to build and distribute the automation environment.

  tasks:
    - title: Build an execution environment
      description: |-
        ##To build an execution environment:

        An automation execution environment must contain the following:
         - Ansible Core 2.16 or later
         - Python 3.10 or later
         - Ansible Runner
         - Ansible content collections and their dependencies
         - System dependencies

        Ansible Builder is a command line tool that automates the process of building automation execution environments by using metadata defined in various Ansible Collections or created by the user.

        For more information about Ansible Builder and execution environments, see: 
        - [Using Ansible Builder](https://docs.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.5/html-single/creating_and_using_execution_environments/index#assembly-using-builder)
        - [Creating and Consuming Execution Environments](https://docs.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.5/html-single/creating_and_using_execution_environments/index)
   
    - title: View an execution environment
      description: |-
        ##To view an execution environment:

        1. From the navigation panel, select **Automation Execution** > **Infrastructure** > **Execution Environments**. 
        2. Click an execution environment to view its details. 
          As part of the initial setup, a **Control Plane Execution Environment**, a **Default execution environment**, and a **Minimal execution environment** are created to help you get started, but you can also create your own.

    - title: Add an execution environment to a job template
      description: |-
        ##To add an execution environment to a job template:

        ###Prerequisites:
          - You have access to an execution environment created using ansible-builder as described in [Building an execution environment](https://docs.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.5/html-single/using_automation_execution/index#ref-controller-build-exec-envs). 
              Use the automation controller UI to specify the execution environment to use in your job templates.
          - You have the appropriate permissions to use an execution environment in a job. 
          - For jobs or jobs template that use an execution environment with an assigned credential, ensure that the credential contains a username, host, and password.

        ###Procedure:
          1. From the navigation panel, select **Automation Execution** > **Infrastructure** > **Execution Environments**.
          2. Click **Create execution environment**.
          3. Enter the appropriate details into the required fields.
          4. Click **Create execution environent**.
          5. To add an execution environment to a job template, specify it in the **Execution environment** field of the job template.

           When you have added an execution environment to a job template, those templates are listed in the **Templates tab** of the execution environment.

           For more information, see [Execution environments](https://docs.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.5/html-single/using_automation_execution/index#assembly-controller-execution-environments).
      
      review:
        instructions: |-
          #### To verify that you've added an execution environment:
          Is the execution environment listed on the **Execution Environments** list view?
        failedTaskHelp: Try the steps again.
      summary:
        success: You have viewed the details of your environment!
        failed: 

  conclusion: You successfully completed the building an execution environment steps! If you
    want to learn how to build a decision environment, take the **Building a decision environment** quick start.

  nextQuickStart: [build-decision-environment]
  