metadata:
  name: view-environment
  # you can add additional metadata here
  instructional: true
spec:
  displayName: Environments
  durationMinutes: 5
  # Optional type section, will display as a tile on the card
  type:
    text: Automation operator
    # 'blue' | 'cyan' | 'green' | 'orange' | 'purple' | 'red' | 'grey'
    color: grey
  # - The icon defined as a base64 value. Example flow:
  # 1. Find an .svg you want to use, like from here: https://www.patternfly.org/v4/guidelines/icons/#all-icons
  # 2. Upload the file here and encode it (output format - plain text): https://base64.guru/converter/encode/image
  # 3. compose - `icon: data:image/svg+xml;base64,<base64 string from step 2>`
  # - If empty string (icon: ''), will use a default rocket icon
  # - If set to null (icon: ~) will not show an icon
  icon: data:image/svg+xml;base64,PCEtLSBHZW5lcmF0ZWQgYnkgSWNvTW9vbi5pbyAtLT4KPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjUxMiIgaGVpZ2h0PSI1MTIiIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj4KPHRpdGxlPjwvdGl0bGU+CjxnIGlkPSJpY29tb29uLWlnbm9yZSI+CjwvZz4KPHBhdGggZD0iTTQ0OCA2NHY0MTZoLTMzNmMtMjYuNTEzIDAtNDgtMjEuNDktNDgtNDhzMjEuNDg3LTQ4IDQ4LTQ4aDMwNHYtMzg0aC0zMjBjLTM1LjE5OSAwLTY0IDI4LjgtNjQgNjR2Mzg0YzAgMzUuMiAyOC44MDEgNjQgNjQgNjRoMzg0di00NDhoLTMyeiI+PC9wYXRoPgo8cGF0aCBkPSJNMTEyLjAyOCA0MTZ2MGMtMC4wMDkgMC4wMDEtMC4wMTkgMC0wLjAyOCAwLTguODM2IDAtMTYgNy4xNjMtMTYgMTZzNy4xNjQgMTYgMTYgMTZjMC4wMDkgMCAwLjAxOS0wLjAwMSAwLjAyOC0wLjAwMXYwLjAwMWgzMDMuOTQ1di0zMmgtMzAzLjk0NXoiPjwvcGF0aD4KPC9zdmc+Cg==
  
  description: |-
    Viewing execution and decision environments.
  introduction: |-
   View your execution and decision environments, and their details.

   Platform administrators and automation developers have the permissions to create environments. 
   As an automation operator you can view environments and their details.

  tasks:
    - title: View an execution environment
      description: |-
        ##To view an execution environment:

        Automation execution environments create a common language for communicating automation dependencies, and offer a standard way to build and distribute the automation environment.

        1. From the navigation panel, select **Automation Execution** > **Infrastructure** > **Execution Environments**. 
        2. Click an execution environment to view its details. 
          As part of the initial setup, a **Control Plane Execution Environment**, a **Default execution environment**, and a **Minimal execution environment** are created to help you get started.

          For more information, see [Execution environments](https://docs.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.5/html-single/using_automation_execution/index#assembly-controller-execution-environments).

    - title: View a decision environment
      description: |-
        ##To view a decision environment:

        Decision environments are a container image to run Ansible rulebooks. 
        They create a common language for communicating automation dependencies, and give a standard way to build and distribute the automation environment. 
        The default decision environment is found in the Ansible-Rulebook.

        1. From the navigation panel, select **Automation Decisions** > **Decision Environments**. 
        2. Click a decision environment to view its details. 
          As part of the initial  setup a **Default Decision Environment** is created. 

          For more information, see [Decision environments](https://docs.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.5/html/using_automation_decisions/eda-decision-environments#eda-build-a-custom-decision-environment).

  conclusion: You successfully completed the viewing an environment steps! If you
    want to learn how to execute an inventory, take the **Inventories** quick start.

  nextQuickStart: [execute-an-inventory]
  